import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";

// Next.js 16 renamed `middleware` to `proxy` (same runtime, nodejs-only).
// This performs an optimistic, cookie-only auth check — it must not hit
// the database. See node_modules/next/dist/docs/.../authentication.md.
export default auth((req) => {
  // Check req.auth?.user, not just req.auth — if auth() ever hits an
  // internal error (misconfiguration, decoding failure), some paths
  // resolve to a truthy-but-empty auth object rather than null. Treating
  // that as "logged in" would fail open; requiring a populated user fails
  // closed instead.
  const isLoggedIn = Boolean(req.auth?.user);
  const isLoginPage = req.nextUrl.pathname === "/login";

  if (!isLoggedIn && !isLoginPage) {
    return NextResponse.redirect(new URL("/login", req.nextUrl));
  }

  if (isLoggedIn && isLoginPage) {
    return NextResponse.redirect(new URL("/outliers", req.nextUrl));
  }
});

export const config = {
  // robots.txt must stay public/unredirected — it's generated by
  // app/robots.ts and needs to be reachable by crawlers without a session.
  matcher: ["/((?!api|_next/static|_next/image|favicon.ico|robots.txt).*)"],
};
